### PR TITLE
Basic image rendering in messages with no image formatting

### PR DESCRIPTION
**Pull request by Sarah-Shahinpour**
I followed what was suggested for Images (Part 1) and used regular expressions to render images in messages. I will improve later by formatting the images, improving the regular expression, and validating the URL.

### CODE REVIEW

**Comment by AhmedAlzubairi1** [comment]
Why did you get rid of the if statement in doPost? What does that change?

**Review by AhmedAlzubairi1 — COMMENTED** [review]
Why did you get rid of the if statement in doPost? What does that change?

**Comment by Sarah-Shahinpour** [comment]
> Why did you get rid of the if statement in doPost? What does that change?

When I check my commits, it doesn't show I deleted any if statements. Could you maybe send a screenshot?

**Comment by AhmedAlzubairi1** [comment]
I went to your files changed and saw it. I don't see it now however, I might have made a mistake. I'll approve it now.

**Review by AhmedAlzubairi1 — APPROVED** [review]

**Comment by Sarah-Shahinpour** [comment]
No worries! thank you!!

**Pull request merged**
