### PR TITLE
Ahmed chart

### PR DESCRIPTION
**Pull request by AhmedAlzubairi1**
Added code to display a bar chart

### CODE REVIEW

**Review by Sarah-Shahinpour — COMMENTED** [review]
Hi! Would you be able to change the formatting a little? I think it might be more consistent if lines: 7, 18, and 33-37 were shifted towards the left and lines: 19-23, 30, and 41 were shifted towards the right. I also think the content in between the script tags on lines 7 and 41 should be indented to the right. Could you also make some of the lines with comments a little shorter by splitting them into multiple lines?

**Comment by AhmedAlzubairi1** [comment]
What do you mean splitting them to multiple lines?

**Comment by Sarah-Shahinpour** [comment]
Just continuing the longer comments onto the next line. For example, line 31 could be turned into two comments like this:
//Note, the chart_options vary with every chart you use. 
//Since we are using the bar chart option, you can use height, width, title, and font size.

**Comment by AhmedAlzubairi1** [comment]
I've made the fixes. Just waiting approval.

**Comment by Sarah-Shahinpour** [comment]
Hi! The comments look better, but I still see a few inconsistencies with the formatting. I don't want to be too picky about it, but it can make your code hard to read and understand. I'm going to send a message in the chat to see if Heather can give us her opinion!

**Comment by AhmedAlzubairi1** [comment]
What else do you see that is inconsistent?

**Review by heatherzheng — APPROVED** [review]

**Pull request merged**
